### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by mehdibo** [bkader/ci-gettext-hook#1]
There is a 500 Error in the demo

**Comment by bkader** [comment]
Thanks for reporting this. I have deleted the demo by mistake a long while ago. I am setting in it up back. Give me few minutes, I am transfering files. (v3.1.7).

**Comment by bkader** [comment]
The demo is up and running.

**Comment by mehdibo** [comment]
Thanks! new problem again, language is not switching, should I open a new issue?

**Comment by bkader** [comment]
On the demo or on your installation? On the demo it's switching.

**Comment by mehdibo** [comment]
No on my Installation, the demo is working perfectly.

**Comment by bkader** [comment]
Can you please check you logs and tell me what's said there. Set your *log_threshold** to **1** in config.php.  

    $config['log_threshold'] = 1;

And don't forget to set your base URL.

**Comment by mehdibo** [comment]
I'm opening a new issue with more details
